"""Renders .arbite/AGENTS.md: a self-describing reference doc written by `arbite init`.

Kept in the package rather than hand-maintained separately so it can't drift
from the actual CLI -- the command reference section is rendered straight
from argparse's own --help output for the installed version.
"""

from __future__ import annotations

from datetime import date

from . import __version__
from .ticket import FIELD_ORDER, STATUSES, TIERS, TYPES

# Vocabularies are interpolated from the ticket module's own constants rather
# than spelled out, so this doc cannot drift from what the CLI actually
# accepts -- it previously advertised a `frontier` tier that `create` and
# `list --tier` both rejected.
FIELD_NOTES = {
    "id": "unique ticket id, e.g. tic-a1b2 -- generated by `arbite create`, never set by hand",
    "title": "short human-readable summary",
    "status": f"{' | '.join(STATUSES)} -- mirrors the ticket's folder, kept in sync by every "
    "arbite command. 'raw' means unclassified and not yet workable (see `arbite raw` / "
    "`arbite fetch`) and is excluded from `arbite list next`",
    "type": f"{' | '.join(TYPES)} -- memo is produced by 'arbite raw' for requests to update "
    "project notes/documentation; wish is produced by 'arbite raw wish' for wishlist items "
    "(reclassified as 'feature' and filed in .arbite/wishlist/ when classified, not opened as work)",
    "tier": f"{' | '.join(TIERS)} -- the **agent capability tier** required to work the "
    "ticket: how capable the agent must be, ascending. Not urgency (that's `priority`) and "
    "not specialization (that's `domain`). An agent is either told its own tier by the "
    "harness or self-assesses from its model class, and should only claim tickets at or "
    "below that tier",
    "domain": "what kind of agent/tool this needs, e.g. mesh, image_gen, audio_gen, ui, io -- drives routing",
    "epic": "the larger initiative this ticket belongs to, e.g. mesh-pipeline -- a freeform grouping label for filtering (list/next --epic), not a structural dependency or a ticket id",
    "priority": "numeric urgency index, lower = more urgent (e.g. 1 is highest priority) -- used to order which workable ticket to pick up next; unset (null) sorts last",
    "tags": "freeform list, for human/codebase-area search -- distinct from domain",
    "assignee": "agent id currently working the ticket, e.g. claude.haiku.001, or null if unclaimed",
    "depends_on": "list of other ticket ids that must close first (structural)",
    "blocked_by": "freeform reason OR a ticket id -- why it's stalled, only meaningful when status: blocked",
    "created": "creation timestamp to the second (YYYY-MM-DDTHH:MM:SS)",
    "updated": "timestamp of the most recent status change (YYYY-MM-DDTHH:MM:SS)",
    "closed": "close timestamp to the second (YYYY-MM-DDTHH:MM:SS), null until closed -- the leading YYYY-MM drives which closed/YYYY-MM/ folder it archives into",
}


def render(parser, subparsers_by_name: dict) -> str:
    lines = []
    lines.append("# AGENTS.md")
    lines.append("")
    lines.append(
        f"_Auto-generated by `arbite init` (arbite {__version__}) on {date.today().isoformat()}. "
        "Regenerated every time `arbite init` runs in this directory -- hand edits here will be "
        "overwritten on the next `arbite init`; if this content needs to change, edit the package's "
        "docs template instead. This file is not auto-discovered -- point your project's CLAUDE.md "
        "(or similar) at it explicitly, e.g. a line like 'read .arbite/AGENTS.md', if you want "
        "agents to find arbite._"
    )
    lines.append("")
    lines.append("## What this is")
    lines.append("")
    lines.append(
        "`arbite` is a low-tech, file-based ticketing system that lives inside this git repo. "
        "Tickets are markdown files with YAML frontmatter, stored under `.arbite/`, moved between "
        "folders as their status changes -- no database, no server. It exists so multiple AI agents "
        "(and humans) can pick up tasks, track state, and leave a clean git history of what happened "
        "and when."
    )
    lines.append("")
    lines.append(
        "**Any agent or human working in this repo should use `arbite` for creating, claiming, "
        "blocking, shelving, closing, and reopening tasks instead of ad hoc notes or files.** The ticket's folder location "
        "is the single source of truth for its state -- an agent's own memory of what it was doing is "
        "only a hint, and must be checked against the ticket's actual location before being trusted. "
        "Agents should also prefer `arbite note` over directly editing a ticket file to leave progress "
        "notes -- it timestamps and attributes the entry consistently instead of relying on freeform "
        "hand edits."
    )
    lines.append("")
    lines.append("## Directory layout")
    lines.append("")
    lines.append("```")
    lines.append(".arbite/")
    lines.append("  raw/             unclassified quick captures -- not workable yet, see below")
    lines.append("  open/            actionable, unclaimed")
    lines.append("  in_progress/     claimed, being worked")
    lines.append("  blocked/         stalled, see blocked_by")
    lines.append("  shelved/         shelved, parked for later")
    lines.append("  wishlist/        reclassified wishes (type: feature) -- not work until promoted")
    lines.append("  planning/        planning/roadmap notes and scratch docs -- not tickets")
    lines.append("  closed/YYYY-MM/  archived by close date")
    lines.append("  agents/          one scratchpad file per agent identity")
    lines.append("  AGENTS.md        this file")
    lines.append("```")
    lines.append("")
    lines.append(
        "Status is represented by folder location, not just a frontmatter field -- `status` mirrors "
        "the folder and is kept in sync by every state-changing command in the same operation. "
        "Filenames stay stable across moves, so `git log --follow` on a ticket file traces its full "
        "lifecycle as folder-move commits."
    )
    lines.append("")
    lines.append("## Ticket frontmatter fields")
    lines.append("")
    for field_name in FIELD_ORDER:
        lines.append(f"- `{field_name}` -- {FIELD_NOTES.get(field_name, '')}")
    lines.append("")
    lines.append(
        "`depends_on` (structural, ticket ids) and `blocked_by` (freeform, human-readable) are "
        "deliberately separate fields -- don't collapse them. `tier` (capability level) and `domain` "
        "(specialization) are independent axes. `domain` (routing) and `tags` (search) serve different "
        "purposes even though both are strings. `priority` (urgency) is independent of `tier` "
        "(capability): a trivial chore can still be urgent. `epic` groups tickets under a larger "
        "initiative (e.g. 'mesh-pipeline') -- it's a freeform label for filtering, not a structural "
        "dependency. When choosing between workable tickets, pick the one with the lowest `priority` "
        "number first."
    )
    lines.append("")
    lines.append("## Agent identity and resuming work")
    lines.append("")
    lines.append(
        "**Know your tier before you claim.** `tier` (`" + " | ".join(TIERS) + "`, ascending) is "
        "the agent capability tier a ticket requires. Either the harness tells you your own tier, "
        "or you self-assess from your model class -- the `company.model` prefix of your agent id "
        "(e.g. `claude.haiku` is a lower tier than `claude.opus`). Claim tickets at or below your "
        "tier, and pass it as `arbite list next --tier <your tier>` so you are only offered work "
        "you can actually do. Tier is independent of `priority` (urgency) and `domain` "
        "(specialization): a trivial chore can be urgent, and a low-tier ticket can still be "
        "audio_gen-only."
    )
    lines.append("")
    lines.append(
        "Agent ids follow `company.model.instance`, e.g. `claude.haiku.001`. Each agent has a "
        "scratchpad at `.arbite/agents/<agent_id>.md` for recording what it's currently working on. "
        "To resume across sessions: check your own scratchpad for a last-known ticket id, then verify "
        "that ticket is still in `.arbite/in_progress/` with `assignee` matching your own id -- the "
        "ticket's folder is ground truth, the scratchpad is only a hint. If the scratchpad is absent, "
        "stale, or mismatched, fall back to scanning `.arbite/in_progress/` for a ticket assigned to you."
    )
    lines.append("")
    lines.append("## Typical workflow")
    lines.append("")
    lines.append("```")
    lines.append("arbite list --status open --domain mesh --tier medium   # find something to work")
    lines.append("arbite list next --tier high                            # grab the next workable open ticket")
    lines.append("arbite list next --count 3 --tier high                  # ...or a batch of three")
    lines.append("arbite list next --epic mesh-pipeline                   # next workable ticket in an epic")
    lines.append("arbite list next --epic classification                  # next raw ticket needing triage")
    lines.append('arbite search --params title,body "LOD pop-in"          # find tickets by text')
    lines.append('arbite raw feature "add per-mesh LOD"                   # quick capture; classify later')
    lines.append('arbite raw wish "fly-through camera preview"            # capture a wish; reclassify + file it later')
    lines.append("arbite list raw                                         # raw backlog awaiting classification")
    lines.append("arbite fetch                                            # pull the oldest raw ticket to classify")
    lines.append("arbite fetch feature                                    # ...or the oldest raw ticket of one type")
    lines.append('arbite move tic-a1b2 /wishlist                          # file a reclassified wish into wishlist/')
    lines.append("arbite show tic-a1b2                                    # read it in full")
    lines.append("arbite claim tic-a1b2 --agent claude.haiku.001          # take it")
    lines.append('arbite note tic-a1b2 claude.haiku.001 "progress update" # ...do the work, log progress...')
    lines.append('arbite block tic-a1b2 --reason "waiting on tic-c3d4"    # if stalled')
    lines.append("arbite unblock tic-a1b2 --agent claude.haiku.001        # when the blocker clears")
    lines.append('arbite release tic-a1b2 --agent claude.haiku.001 \\')
    lines.append('    --reason "wrong tier for me"                        # hand it back, unclaimed')
    lines.append('arbite shelve tic-a1b2 --reason "parked for later"      # if deprioritized')
    lines.append('arbite unshelve tic-a1b2 --reason "back in scope"       # bring it back to open')
    lines.append("arbite close tic-a1b2                                   # when done")
    lines.append("arbite reopen tic-a1b2                                  # if it turns out not to be done after all")
    lines.append("```")
    lines.append("")
    lines.append("## Working with arbite from a script or agent loop")
    lines.append("")
    lines.append(
        "**Claim in one step.** `arbite list next --claim <agent_id>` selects the most urgent "
        "workable ticket *and* claims it atomically. Prefer it over running `list next` and then "
        "`claim`: between those two commands another agent can take the ticket you were just "
        "handed, and you would both work it. A plain `arbite claim` is also a compare-and-swap -- "
        "claiming a ticket already assigned to someone else fails unless you pass `--force`."
    )
    lines.append("")
    lines.append(
        "**Pull a batch with `--count N`.** `arbite list next --count 3` returns the 3 most "
        "urgent workable tickets instead of 1, so a dispatcher can fan work out to several "
        "agents in one query; adding `--claim <agent_id>` claims up to N of them. Each claim "
        "is individually atomic, so if another agent races you for one the rest still succeed "
        "-- a short batch is a real result, and the count actually claimed is reported on "
        "stderr. `--count` also caps a plain `list`, `--topo` (rows) or `--tree` (top-level "
        "roots, never truncating a subtree)."
    )
    lines.append("")
    lines.append(
        "**Parse JSON, not tables.** `--json` on `list`, `list next`, `fetch`, `show`, `search`, "
        "`deps` and `doctor` emits machine-readable output whose field names match the "
        "frontmatter. The human table format is not a stable interface."
    )
    lines.append("")
    lines.append("**Exit codes** let a shell loop branch without matching on message text:")
    lines.append("")
    lines.append("```")
    lines.append("0  success, with results")
    lines.append("1  error (bad arguments, ambiguous ticket id, refused claim, ...)")
    lines.append("2  the query ran fine but matched nothing -- e.g. no workable ticket right now")
    lines.append("3  `arbite doctor` found integrity problems")
    lines.append("```")
    lines.append("")
    lines.append("```")
    lines.append("arbite list next --tier medium --claim claude.haiku.001 --json > ticket.json")
    lines.append("case $? in")
    lines.append("  0) ;;                       # got one, work it")
    lines.append("  2) echo 'nothing ready'; exit 0 ;;")
    lines.append("  *) echo 'arbite failed' >&2; exit 1 ;;")
    lines.append("esac")
    lines.append("```")
    lines.append("")
    lines.append(
        "**Check integrity when something looks wrong.** Tickets are plain files in a git repo, so "
        "a hand `mv`, a merge, a rebase or an interrupted write can leave a ticket's frontmatter "
        "disagreeing with the folder it sits in. `arbite doctor` reports that drift (plus duplicate "
        "ids, dangling dependencies, unsatisfiable dependency cycles, mis-filed closed tickets, "
        "in_progress tickets with no assignee, and blocked tickets with no reason). `arbite doctor "
        "--fix` repairs the unambiguous ones -- frontmatter is rewritten to match the folder, since "
        "**the folder is the source of truth** -- and only reports anything needing a judgement call."
    )
    lines.append("")
    lines.append(
        "A human can also scaffold a ticket to fill in by hand later with `arbite create --blank` "
        "(optionally combined with any of --title/--type/--tier/--domain for whatever's already "
        "known). It fills in only the structural fields and leaves the rest as TODO placeholders, "
        "with a body warning telling agents not to claim it until it's been completed and saved."
    )
    lines.append("")
    lines.append(
        "A **raw** ticket (`arbite raw <memo|feature|bug|wish> <message>`) is a deliberately "
        "unclassified quick capture of a brief request: status `raw`, filed in `.arbite/raw/` "
        "(not `open/`, and never returned by `arbite list next`). It sets only the `type` and a "
        "placeholder title (`<type> (raw): Requires Classification`), auto-groups the ticket under "
        "the `classification` epic (so triage/classification jobs can discover it with "
        "`arbite list next --epic classification`), and its body lists what still needs to be "
        "filled in -- a real title, `tier`, `domain`, a real `epic`, `priority`, and an expanded "
        "description based on the original request -- before the ticket can be claimed or worked. "
        "Raw tickets exist so a thought isn't lost, not as workable tasks: treat them as requiring "
        "triage, and classify them before picking them up. A `memo` raw ticket is primarily a "
        "request to update any project notes / documentation that is being maintained, rather "
        "than a code change. The one-word forms `arbite bug <message>`, `arbite feature "
        "<message>`, `arbite memo <message>` and `arbite wish <message>` are shorthand for the "
        "same-named `arbite raw <type> <message>` invocation -- an identical raw ticket, just "
        "a shorter command. `arbite list raw` renders the whole raw backlog as a running todo "
        "list until a classification run drains it: grouped by type (memo/feature/bug/wish), "
        "one line per ticket showing its id and the request text it was captured from, oldest "
        "first -- so a human or triage pass can scan in one screen what is still waiting to be "
        "classified, then pull each ticket with `arbite fetch`."
    )
    lines.append("")
    lines.append(
        "A **wish** raw ticket (`arbite raw wish <message>`) is a wishlist item, not ordinary "
        "feature work. Its body notes that wishlist items are to be reclassified as `feature`, "
        "classified with the correct tags, an expanded description, an analysis of the request, "
        "and a possible epic, and then filed in the `.arbite/wishlist/` folder (created if it "
        "doesn't exist) with `arbite move <id> /wishlist` -- not opened or claimed as work. "
        "`arbite fetch wish` (or `arbite fetch`) pulls it and its `derived_note` gives these same "
        "instructions."
    )
    lines.append("")
    lines.append(
        "**`arbite move <id> <folder>`** moves a ticket's file to a folder under the arbite "
        "root without changing its status or frontmatter. `<folder>` is root-relative: `/` is "
        "the arbite root itself, `/wishlist` is `.arbite/wishlist/`, and a longer path like "
        "`/planning/ideas` nests folders. The destination folder is created if it doesn't exist. "
        "Use it to file tickets into non-status buckets (wishlist/, planning/); use the status "
        "commands (claim/block/close/...) for moves that should change state."
    )
    lines.append("")
    lines.append(
        "**`arbite fetch [type]`** pulls the single oldest raw ticket (by `created` date, "
        "optionally restricted to a type) and prints it like `arbite show` would, with a "
        "`derived_note` injected at the top -- a JSON field in `--json` mode, a leading block in "
        "text mode -- giving brief instructions: classify the ticket (title/tier/domain/epic/"
        "priority/description), then either set `status` to `open` (if you're only triaging, so "
        "someone else can pick it up via `arbite list next`) or `arbite claim` it immediately (if "
        "you're going to work it yourself right now). A `wish` raw ticket is classified "
        "differently: reclassify it as `feature` and file it in `.arbite/wishlist/` instead."
    )
    lines.append("")
    lines.append("## Full command reference")
    lines.append("")
    lines.append(
        "Rendered directly from `arbite --help` and each subcommand's `--help` for the installed "
        "version, so it always matches the actual CLI. Every command also supports `-h`/`--help` "
        "directly if this file is ever out of date."
    )
    lines.append("")
    lines.append("```")
    lines.append(parser.format_help().rstrip())
    lines.append("```")
    lines.append("")
    for name, subparser in subparsers_by_name.items():
        lines.append(f"### `arbite {name}`")
        lines.append("")
        lines.append("```")
        lines.append(subparser.format_help().rstrip())
        lines.append("```")
        lines.append("")

    return "\n".join(lines) + "\n"
