"""Renders .arbite/AGENTS.md: a self-describing reference doc written by `arbite init`.

Two jobs, one file: it explains the workflow, and it carries the command
reference. Kept in the package rather than hand-maintained per repo so it can't
drift from the actual CLI -- the command section is rendered straight from the
installed argparse parsers, and the prose interpolates the same vocabulary
constants the CLI validates against (it previously advertised a `frontier` tier
that `create` and `list --tier` both rejected).

Written terse on purpose: this file is read into an agent's context at the start
of every task, so it is optimised for facts-per-token rather than for prose.
Boilerplate that would otherwise repeat once per command is stated once and
cross-referenced, and argparse's longer per-command descriptions are dropped
because the prose sections already carry what they say -- `arbite <cmd> -h`
still prints them in full.

TICKET_ID_HELP / TICKET_ID_HELP_READONLY / JSON_HELP / MESSAGE_HELP live here
(cli.py imports them) so the renderer can collapse the copies of that
boilerplate into a single cross-reference without the two copies drifting apart.
"""

from __future__ import annotations

import argparse
import re
from datetime import date

from . import __version__
from .ticket import CLASSIFICATION_EPIC, FIELD_ORDER, STATUSES, TIER_VALUES, TYPES

# ---------------------------------------------------------------------------
# Help text shared with the CLI (single source of truth for both the real
# --help output and the dedupe substitutions in the renderer below).
# ---------------------------------------------------------------------------

TICKET_ID_HELP = (
    "ticket id or any wildcard (substring) match, e.g. 'f6' or 'tic-f607' both "
    "resolve to tic-f607; an exact id always wins, and for commands that modify "
    "a ticket an ambiguous match is an error listing the candidates rather than "
    "a guess"
)

# Read-only commands keep the old convenience: a guess there costs nothing.
TICKET_ID_HELP_READONLY = (
    "ticket id or any wildcard (substring) match, e.g. 'f6' or 'tic-f607' both "
    "resolve to tic-f607; if several tickets match, the first alphabetically is used"
)

JSON_HELP = (
    "emit machine-readable JSON on stdout instead of a formatted table "
    "(field names match the ticket frontmatter); exit code 2 means the query "
    "ran but matched nothing"
)

MESSAGE_HELP = (
    "brief request to capture, e.g. \"users can't save without auth\" "
    "(joined with spaces if multiple words)"
)

# Per-field descriptions for the frontmatter table, keyed by field name.
# Interpolating the vocabulary constants keeps the doc honest about what the
# CLI actually accepts.
FIELD_NOTES = {
    "id": "unique ticket id, e.g. tic-a1b2 -- generated by `arbite create`, never set by hand",
    "title": "short human-readable summary",
    "status": f"{' | '.join(STATUSES)} -- mirrors the folder, kept in sync by every arbite "
    "command; 'raw' = unclassified, not workable, never offered by `list next` (see Triage)",
    "type": f"{' | '.join(TYPES)} -- 'memo' (from `raw memo`) = update project notes/docs, not "
    "code; 'wish' (from `raw wish`) = a wishlist item, reclassified as 'feature' and filed, "
    "never worked",
    "tier": f"{TIER_VALUES} -- the **agent capability tier** required to work the ticket: how "
    "capable the agent must be, ascending. The harness tells you your tier, or you self-assess "
    "from your model class (the company.model prefix of your agent id, e.g. claude.haiku sits "
    "below claude.opus); claim only at or below your tier",
    "domain": "what kind of agent/tool this needs, e.g. mesh, image_gen, audio_gen, ui, io -- "
    "drives routing",
    "epic": "the larger initiative this ticket belongs to, e.g. mesh-pipeline -- a freeform "
    "grouping label for filtering (`list [next] --epic`), not a dependency or ticket id",
    "priority": "numeric urgency index, lower = more urgent (1 is highest) -- orders which "
    "workable ticket to pick up next; unset (null) sorts last",
    "tags": "freeform list, for human/codebase-area search -- distinct from domain",
    "assignee": "agent id currently working the ticket, e.g. claude.haiku.001, or null if unclaimed",
    "depends_on": "list of other ticket ids that must close first (structural)",
    "blocked_by": "freeform reason OR a ticket id -- why it's stalled, only meaningful when "
    "status: blocked",
    "created": "creation timestamp (YYYY-MM-DDTHH:MM:SS); a bare YYYY-MM-DD also validates",
    "updated": "timestamp of the most recent status change",
    "closed": "close timestamp, null until closed -- its leading YYYY-MM picks the closed/YYYY-MM/ "
    "folder it archives into",
}

# ---------------------------------------------------------------------------
# Compaction helpers
# ---------------------------------------------------------------------------

# Boilerplate that would otherwise appear once per command: each entry is
# (verbatim argparse help text, short cross-reference to render instead).
_SUBSTITUTIONS = (
    (TICKET_ID_HELP, "see 'Ticket ids' under Conventions"),
    (TICKET_ID_HELP_READONLY, "see 'Ticket ids' under Conventions"),
    (JSON_HELP, "JSON output (see Conventions)"),
    (MESSAGE_HELP, "the request text (multiple words are joined with spaces)"),
    (
        "Tier is how capable the agent must be, ascending -- not how urgent the work "
        "is (that's priority, lower = more urgent) and not what specialization it "
        "needs (that's domain). Those axes are independent: a trivial chore can be "
        "urgent, and a low-tier ticket can still be audio_gen-only. An agent is "
        "either told its own tier by the harness or self-assesses from its model "
        "class (the company.model prefix of its agent id, e.g. claude.haiku sits "
        "below claude.opus), and should only claim tickets at or below that tier.",
        "See 'tier' under Ticket fields.",
    ),
)

# Actions that take no value, so their label needs no metavar.
_NO_VALUE_ACTIONS = (
    argparse._HelpAction,
    argparse._StoreTrueAction,
    argparse._StoreFalseAction,
    argparse._CountAction,
    argparse._VersionAction,
)


# ANSI/CSI escape sequences. argparse >= 3.14 colours its help output when it
# believes it is writing to a terminal (or when FORCE_COLOR is set, which agent
# harnesses do), and those codes would otherwise end up embedded in the markdown
# as junk like '\x1b[1;34m'. This file is always read as plain text, so they are
# stripped -- see _disable_color() for the belt to this braces.
_ANSI_RE = re.compile(r"\x1b\[[0-9;?]*[ -/]*[@-~]")


def _flat(text: str) -> str:
    """Collapse a wrapped help string onto one line, with no escape codes."""
    return _ANSI_RE.sub("", " ".join((text or "").split()))


def _disable_color(*parsers) -> None:
    """Ask parsers not to colourise their help (a no-op before Python 3.14).

    The renderer strips escapes either way, so this only keeps the intermediate
    text readable when debugging; the parsers are transient ones built for
    `arbite init`, never the ones serving `--help` to a user.
    """
    for parser in parsers:
        if hasattr(parser, "color"):
            parser.color = False


def _shorten(text: str) -> str:
    """Collapse and cross-reference the boilerplate repeated across commands."""
    text = _flat(text)
    for needle, replacement in _SUBSTITUTIONS:
        text = text.replace(needle, replacement)
    return text


def _action_label(action) -> str:
    """`--flag ARG` / `-r/--regex` / `POSITIONAL` for one argparse action."""
    if action.option_strings:
        label = "/".join(action.option_strings)
        if not isinstance(action, _NO_VALUE_ACTIONS) and action.nargs != 0:
            label += " " + (action.metavar or action.dest.upper())
        return label
    return str(action.metavar or action.dest)


def _iter_actions(subparser):
    """Every non-help action of a subparser: positionals and options alike."""
    for action in subparser._actions:
        if isinstance(action, argparse._SubParsersAction) or action.dest == "help":
            continue
        yield action


def _is_shorthand(subparser) -> bool:
    """True for `arbite bug|feature|memo|wish <message>`, the one-word forms of
    `arbite raw <type> <message>`: they are described as shorthands by the CLI
    itself, so their block would just repeat `arbite raw`'s. Detecting it from
    that wording fails safe -- if the wording ever changes they simply render in
    full again, just less tersely.
    """
    return "shorthand for" in _flat(subparser.description or "").lower()


def _usage(subparser) -> str:
    text = _flat(subparser.format_usage())
    return text[len("usage: "):] if text.startswith("usage: ") else text


def render(parser, subparsers_by_name: dict) -> str:
    _disable_color(parser, *subparsers_by_name.values())

    lines: list[str] = []
    add = lines.append

    add("# arbite -- agent guide")
    add("")
    add(
        f"_Auto-generated by `arbite init` (arbite {__version__}) on {date.today().isoformat()}: "
        "every `arbite init` run here rewrites it, so edit the package's docs template rather than "
        "this file. Not auto-discovered -- point your project's CLAUDE.md at it explicitly (e.g. a "
        "line 'read .arbite/AGENTS.md')._"
    )
    add("")

    # -- What this is ------------------------------------------------------
    add("## What this is")
    add("")
    add(
        "`arbite` is a low-tech, file-based ticketing system that lives inside this git repo: tickets "
        "are markdown files with YAML frontmatter under `.arbite/`, moved between folders as their "
        "status changes -- no database, no server -- so several AI agents (and humans) can pick up "
        "tasks, track state, and leave a clean git history of what happened and when."
    )
    add("")
    add(
        "Use `arbite` to create, claim, block, shelve, close and reopen work instead of ad hoc notes "
        "or files. **A ticket's folder is the single source of truth for its state**; an agent's "
        "memory of what it was doing is only a hint, to be checked against the ticket's actual "
        "location. Leave progress with `arbite note` rather than editing the ticket file -- it "
        "appends a timestamped, agent-identified entry to the ticket's `## Notes` section."
    )
    add("")

    # -- Layout ------------------------------------------------------------
    add("## Directory layout")
    add("")
    add("```")
    add(".arbite/")
    add("  raw/            unclassified captures -- not workable (see Triage)")
    add("  open/           actionable, unclaimed")
    add("  in_progress/    claimed, being worked")
    add("  blocked/        stalled -- see blocked_by")
    add("  shelved/        parked for later")
    add("  wishlist/       reclassified wishes (type: feature) -- parked, not work")
    add("  planning/       planning/roadmap notes and scratch docs -- not tickets")
    add("  closed/YYYY-MM/ archived by close date")
    add("  agents/         one scratchpad file per agent identity")
    add("```")
    add("")
    add(
        "Status *is* folder location: `status` mirrors the folder and every state-changing command "
        "updates both at once. Filenames never change on a move, so `git log --follow` on a ticket "
        "file traces its whole lifecycle. `arbite init` creates all of the above, writes this file, "
        "and pre-creates a scratchpad for each id listed under `agents:` in ./arbite.yaml."
    )
    add("")

    # -- Fields ------------------------------------------------------------
    add("## Ticket fields (YAML frontmatter)")
    add("")
    for field_name in FIELD_ORDER:
        add(f"- `{field_name}` -- {FIELD_NOTES.get(field_name, '')}")
    add("")
    add(
        "These axes are independent -- don't collapse them: `depends_on` (structural ticket ids) vs "
        "`blocked_by` (freeform prose); `tier` (capability) vs `domain` (specialization) vs "
        "`priority` (urgency) -- an urgent low-tier chore is possible, and a low-tier ticket can "
        "still be audio_gen-only; `domain` (routing) vs `tags` (search). `epic` groups for filtering "
        "only. Given a choice of workable tickets, take the lowest `priority` number (`list` shows "
        "the more urgent first within a status)."
    )
    add("")

    # -- Identity ----------------------------------------------------------
    add("## Agent identity and resuming work")
    add("")
    add(
        "Agent ids are `company.model.instance`, e.g. `claude.haiku.001`; each agent has a scratchpad "
        "at `.arbite/agents/<agent_id>.md` recording what it is working on. Know your `tier` before "
        "claiming (see Ticket fields) and pass it to `arbite list next --tier <tier>` so you are only "
        "offered work you can actually do."
    )
    add("")
    add(
        "To resume: check your scratchpad for a last-known ticket id, then verify that ticket is "
        "still in `.arbite/in_progress/` with `assignee` matching your own id -- the folder is ground "
        "truth, the scratchpad only a hint. If it is missing, stale or mismatched, scan "
        "`.arbite/in_progress/` for a ticket assigned to you. Identity assignment, collision "
        "avoidance and liveness detection belong to the agent harness, not arbite."
    )
    add("")

    # -- Workflow ----------------------------------------------------------
    add("## Typical workflow")
    add("")
    add("```")
    add("arbite list --status open --domain mesh --tier medium   # find something to work")
    add("arbite list next --tier high                            # next workable open ticket")
    add("arbite list next --count 3 --tier high                  # ...or a batch of three")
    add("arbite list next --epic mesh-pipeline                   # next workable ticket in an epic")
    add("arbite list next --epic classification                  # next raw ticket needing triage")
    add("arbite list raw                                         # raw backlog as a todo list")
    add('arbite search --params title,body "LOD pop-in"          # find tickets by text')
    add('arbite raw feature "add per-mesh LOD"                   # quick capture; classify later')
    add('arbite raw wish "fly-through camera preview"            # capture a wish; file it later')
    add("arbite fetch [type]                                     # oldest raw ticket to classify")
    add("arbite move tic-a1b2 /wishlist                          # file a reclassified wish")
    add("arbite show tic-a1b2                                    # read it in full")
    add("arbite claim tic-a1b2 --agent claude.haiku.001          # take it")
    add('arbite note tic-a1b2 claude.haiku.001 "progress"        # ...do the work, log progress...')
    add('arbite block tic-a1b2 --reason "waiting on tic-c3d4"    # if stalled')
    add("arbite unblock tic-a1b2 --agent claude.haiku.001        # blocker cleared")
    add('arbite release tic-a1b2 --agent claude.haiku.001 --reason "wrong tier for me"')
    add('arbite shelve tic-a1b2 --reason "parked for later"      # if deprioritized')
    add('arbite unshelve tic-a1b2 --reason "back in scope"       # bring it back to open')
    add("arbite close tic-a1b2                                   # when done")
    add("arbite reopen tic-a1b2                                  # if it turns out not to be done")
    add("```")
    add("")
    add(
        "`arbite bug|feature|memo|wish <message>` == `arbite raw <type> <message>`: an identical raw "
        "ticket from a shorter command. Any command takes `-h`/`--help`."
    )
    add("")

    # -- Conventions -------------------------------------------------------
    add("## Conventions (scripts and agent loops)")
    add("")
    add(
        "**Ticket ids.** A ticket id argument is an exact id or any unique wildcard (substring) "
        "match: 'f6' resolves to tic-f607, and an exact id always wins. Commands that modify a ticket "
        "treat an ambiguous match as an error listing the candidates rather than guessing; read-only "
        "commands (`show`, `deps`) take the first alphabetically instead."
    )
    add("")
    add(
        "**Exit codes**, so a shell loop can branch without matching on message text: 0 success with "
        "results; 1 error (bad arguments, ambiguous ticket id, refused claim, ...); 2 the query ran "
        "fine but matched nothing (e.g. no workable ticket right now); 3 `arbite doctor` found "
        "integrity problems."
    )
    add("")
    add("```")
    add("arbite list next --tier medium --claim claude.haiku.001 --json > ticket.json")
    add("case $? in")
    add("  0) ;;                       # got one, work it")
    add("  2) echo 'nothing ready'; exit 0 ;;")
    add("  *) echo 'arbite failed' >&2; exit 1 ;;")
    add("esac")
    add("```")
    add("")
    add(
        "**Parse JSON, not tables.** `--json` on `list`, `list next`, `list raw`, `fetch`, `show`, "
        "`search`, `deps` and `doctor` emits machine-readable output whose field names match the "
        "frontmatter; the human table format is not a stable interface."
    )
    add("")
    add(
        "**Claim in one step.** `arbite list next --claim <agent_id>` selects the most urgent workable "
        "ticket *and* claims it atomically. Prefer it to running `list next` then `claim`: between "
        "those two commands another agent can take the ticket you were just handed, and you would "
        "both work it. A plain `arbite claim` is also a compare-and-swap -- it fails if the ticket is "
        "already assigned to someone else unless you pass `--force`."
    )
    add("")
    add(
        "**Pull a batch with `--count N`.** `arbite list next --count 3` returns the 3 most urgent "
        "workable tickets instead of 1, so a dispatcher can fan work out to several agents in one "
        "query; adding `--claim <agent_id>` claims up to N of them. Each claim is individually atomic, "
        "so if another agent races you for one the rest still succeed -- a short batch is a real "
        "result, and the count actually claimed is reported on stderr. `--count` also caps a plain "
        "`list`, `--topo` (rows) or `--tree` (top-level roots, never truncating a subtree)."
    )
    add("")

    # -- Triage ------------------------------------------------------------
    add("## Triage: raw tickets, wishes, filing, scaffolding")
    add("")
    add(
        f"A **raw** ticket (`arbite raw <memo|feature|bug|wish> <message>`) is a deliberately "
        f"unclassified quick capture: status `raw`, filed in `.arbite/raw/`, never returned by "
        f"`arbite list next`. It sets only `type` plus a placeholder title (`<type> (raw): Requires "
        f"Classification`), auto-groups the ticket under the `{CLASSIFICATION_EPIC}` epic (find them "
        f"with `arbite list next --epic {CLASSIFICATION_EPIC}`), and its body lists what triage must "
        f"fill in -- a real title, `tier`, `domain`, a real `epic`, `priority`, an expanded "
        f"description -- before it can be claimed or worked; a `memo` is a request to update project "
        f"notes/docs rather than change code. Raw tickets exist so a thought isn't lost, not as work: "
        f"classify them before picking them up."
    )
    add("")
    add(
        "`arbite list raw` prints the whole raw backlog as a running todo list -- grouped by type, one "
        "line per ticket (id + the request text it was captured from), oldest first -- until a "
        "classification run drains it."
    )
    add("")
    add(
        "**`arbite fetch [type]`** pulls the single oldest raw ticket (by `created`, optionally of one "
        "type) and prints it like `show`, with a `derived_note` at the top (a JSON field in `--json` "
        "mode, a leading block in text) telling you to classify it "
        "(title/tier/domain/epic/priority/description) and then either set `status` to `open` (if you "
        "are only triaging, so someone else can pick it up via `arbite list next`) or `arbite claim` "
        "it now (if you are working it yourself)."
    )
    add("")
    add(
        "A **wish** raw ticket (`arbite raw wish <message>`) is a wishlist item, not ordinary feature "
        "work: its body (and `fetch`'s `derived_note` for it) says to reclassify it as `feature`, "
        "with correct tags, an expanded description, an analysis of the request and a possible epic, "
        "then file it in `.arbite/wishlist/` -- never open or claim it as work."
    )
    add("")
    add(
        "**`arbite move <id> <folder>`** moves a ticket's file to a root-relative folder (`/` is the "
        "arbite root, `/wishlist` is `.arbite/wishlist/`, `/planning/ideas` nests; created if "
        "missing) without changing its status or frontmatter -- a raw file move for non-status buckets "
        "(wishlist/, planning/). Use the status commands (claim/block/close/...) for moves that should "
        "change state."
    )
    add("")
    add(
        "**Integrity.** Tickets are plain files in a git repo, so a hand `mv`, a merge, a rebase or an "
        "interrupted write can leave a ticket's frontmatter disagreeing with the folder it sits in. "
        "`arbite doctor` reports that drift plus duplicate ids, unreadable tickets, stray/temp files, "
        "dependency cycles, dangling and self dependencies, mis-filed closed tickets, in_progress "
        "tickets with no assignee, and blocked tickets with no reason. `--fix` repairs the "
        "unambiguous ones (frontmatter rewritten to match the folder -- **the folder is the source of "
        "truth** -- and closed tickets moved to their archive month) and only reports what needs a "
        "judgement call."
    )
    add("")

    # -- Commands ----------------------------------------------------------
    add("## Commands")
    add("")
    add(
        "Rendered from the installed version's own parsers, so it always matches the CLI: the usage "
        "line and flags of every command (argparse's longer descriptions are omitted -- `arbite <cmd> "
        "-h` prints them). Each status command moves the ticket file to the matching folder and "
        "updates `status`/`updated` together; `block`, `shelve`, `release`, `unblock`, `reopen` and "
        "`unshelve` also append an automatic timestamped note."
    )
    add("")
    add(
        "Command notes: `release` is how you hand back work you stop part-way (out of scope, out of "
        "context, or the wrong tier) -- it clears the assignee and any block reason so `list next` "
        "offers the ticket again; `unblock` clears `blocked_by` and returns the ticket to "
        "`in_progress/` (`open/` with `--open`), and is preferable to `arbite set status`, which "
        "would leave `blocked_by` populated and the ticket claiming to be stalled; `reopen` clears "
        "the closed date and any block reason and `unshelve` clears the assignee and any block "
        "reason; `set` takes PROPERTY VALUE pairs (any number per call, quote multi-word values, "
        "`''` clears a field), is type-aware (`tags`/`depends_on` comma-separated lists, `priority` "
        "an integer), cannot set the structural `id`, and moves the file when `status` changes; "
        "`depend` adds a dependency (deduplicated), or with one argument clears them all; `search` "
        "matches a ticket if any selected field matches."
    )
    add("")
    add(f"`{_usage(parser)}` -- file-based ticketing system")
    add("")
    for sub_action in parser._actions:
        if isinstance(sub_action, argparse._SubParsersAction):
            for choice in getattr(sub_action, "_choices_actions", []):
                add(f"- `{choice.dest}` -- {_flat(choice.help)}")
            break
    add("")

    shorthands: list[str] = []
    for name, subparser in subparsers_by_name.items():
        if _is_shorthand(subparser):
            # Four near-identical blocks would say the same thing four times.
            shorthands.append(name)
            continue

        add(f"**`arbite {name}`** -- `{_usage(subparser)}`")
        bullets = []
        for action in _iter_actions(subparser):
            required = bool(action.option_strings and action.required)
            help_text = _shorten(action.help)
            if required and help_text.endswith(" (required)"):
                # Already flagged as required on this line.
                help_text = help_text[: -len(" (required)")]
            marker = " (required)" if required else ""
            bullets.append(f"- `{_action_label(action)}`{marker} -- {help_text}")
        if bullets:
            add("")
            lines.extend(bullets)
        add("")
    if shorthands:
        add(
            f"`arbite {'|'.join(shorthands)} <message>` == `arbite raw <type> <message>`: the same "
            "raw ticket of that type (see `arbite raw` above)."
        )
        add("")

    # Last line of defence: no escape code may reach the file, whatever the
    # running argparse version decided to colourise.
    return _ANSI_RE.sub("", "\n".join(lines)) + "\n"
